<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.mujin</groupId>
        <artifactId>mujin-framework</artifactId>
        <version>1.0.0-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <groupId>com.mujin.boot</groupId>
    <artifactId>mujin-boot-starter</artifactId>
    <name>mujin-boot-starter</name>
    <packaging>pom</packaging>
    <modules>
        <module>mujin-web-boot-starter</module>
        <module>mujin-web-security</module>
        <module>mujin-web-cache</module>
        <module>mujin-web-orm</module>
        <module>mujin-web-logging</module>
        <module>mujin-web-document</module>
    </modules>

    <properties>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.mujin.boot</groupId>
                <artifactId>mujin-web-security</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.mujin.commons</groupId>
                <artifactId>commons-web</artifactId>
                <version>${project.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

</project>