<project>
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.mujin.commons</groupId>
        <artifactId>mujin-commons</artifactId>
        <version>1.0.0</version>
    </parent>
    <artifactId>commons-web</artifactId>
    <packaging>jar</packaging>
    <name>commons-web</name>
    <dependencies>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-core</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.tomcat.embed</groupId>
            <artifactId>tomcat-embed-core</artifactId>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>com.mujin.commons</groupId>
            <artifactId>commons-lang</artifactId>
        </dependency>
    </dependencies>
</project>
